[package]
name = "ws"
version = "0.1.0"
authors = ["Rob Baruch <robertbaruch@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.11.0"
native-tls = "0.2.4"
